export type AuditStatus="DRAFT"|"READY"|"APPROVAL_REQUIRED"|"APPROVED"|"DELIVERED"|"FAILED";
export type ApprovalStatus="NOT_REQUIRED"|"PENDING"|"APPROVED"|"REJECTED";
export type AuditSectionKey="executive_summary"|"business_profile"|"visibility"|"visual_intelligence"|"competitors"|"opportunity"|"key_gaps"|"quick_wins"|"recommendations"|"measurement"|"limitations";
export interface AuditEvidenceRef { evidenceId:string; sourceRef?:string; observedAt?:string; confidence:string; observability:string; }
export interface AuditFinding { findingId:string; type:string; priority:string; title:string; description:string; evidenceRefs:AuditEvidenceRef[]; sourceRefs:string[]; confidence:string; observability:string; relatedScore?:string; relatedDimension?:string; recommendedAction?:string; }
export interface AuditRecommendation { recommendationId:string; action:string; reason:string; evidenceRefs:AuditEvidenceRef[]; relatedScoreComponent?:string; confidence:string; estimatedEffort:string; approvalLevel:string; missionType?:string; status:"OPEN"|"APPROVED"|"COMPLETED"|"DISMISSED"; }
export interface AuditQuickWin { quickWinId:string; action:string; reason:string; expectedValueCategory:string; evidenceRefs:AuditEvidenceRef[]; confidence:string; estimatedEffort:string; approvalRequired:boolean; status:"OPEN"|"APPROVED"|"COMPLETED"|"DISMISSED"; }
export interface AuditSection { key:AuditSectionKey; title:string; content:Record<string,unknown>; evidenceRefs:AuditEvidenceRef[]; confidence:string; observability:string; }
export interface MapSparkAudit { auditId:string; businessId:string; generatedAt:string; generatedBy:string; methodologyVersion:string; visibilityScore:unknown; visibilityScoreVersion:string; opportunityScore:unknown; opportunityScoreVersion:string; competitorBenchmark:unknown|null; evidenceCoverage:number; confidence:unknown; sections:AuditSection[]; findings:AuditFinding[]; recommendations:AuditRecommendation[]; quickWins:AuditQuickWin[]; nextAction:ScoutNextAction|null; approvalStatus:ApprovalStatus; evidenceRefs:AuditEvidenceRef[]; sourceRefs:string[]; limitations:string[]; generatedArtifacts:Record<string,unknown>[]; status:AuditStatus; }
export interface ScoutNextAction { actionType:string; reason:string; evidenceRefs:AuditEvidenceRef[]; confidence:string; approvalLevel:string; missionType?:string; status:"RECOMMENDED"|"QUEUED"|"BLOCKED"|"COMPLETED"; }
