import type { AuditGeneratorInput, AuditGenerationResult } from "./audit-inputs";
import type { AuditSection, MapSparkAudit, ScoutNextAction } from "./audit-types";
import { collectAuditEvidence } from "./lineage";
export function generateAudit(input:AuditGeneratorInput):AuditGenerationResult { const sections:AuditSection[]=[
  {key:"executive_summary",title:"Executive Summary",content:{visibilityScore:input.visibilityScore,opportunityScore:input.opportunityScore,nextAction:"See generated next action"},evidenceRefs:[],confidence:"UNKNOWN",observability:"OBSERVED_PRESENT"},
  {key:"business_profile",title:"Business Profile",content:{business:input.business},evidenceRefs:[],confidence:"UNKNOWN",observability:"OBSERVED_PRESENT"},
  {key:"visibility",title:"Visibility Score",content:{score:input.visibilityScore},evidenceRefs:[],confidence:"UNKNOWN",observability:"OBSERVED_PRESENT"},
  {key:"visual_intelligence",title:"Visual Intelligence",content:{observations:input.multimodalObservations??[],verificationNote:"Model observations remain UNVERIFIED, are not evidence records, and do not affect opportunity scoring."},evidenceRefs:[],confidence:"UNKNOWN",observability:input.multimodalObservations?.length?"OBSERVED_PRESENT":"NOT_OBSERVABLE"},
  {key:"competitors",title:"Competitor Landscape",content:{gaps:input.competitorGaps,benchmark:input.competitorBenchmark},evidenceRefs:[],confidence:input.competitorBenchmark?"MEDIUM":"UNKNOWN",observability:input.competitorBenchmark?"OBSERVED_PRESENT":"NOT_OBSERVABLE"},
  {key:"opportunity",title:"Opportunity Score",content:{score:input.opportunityScore},evidenceRefs:[],confidence:"UNKNOWN",observability:"OBSERVED_PRESENT"},
  {key:"key_gaps",title:"Key Gaps",content:{},evidenceRefs:[],confidence:"UNKNOWN",observability:"NOT_OBSERVABLE"},
  {key:"quick_wins",title:"Quick Wins",content:{quickWins:input.quickWins},evidenceRefs:[],confidence:"UNKNOWN",observability:input.quickWins.length?"OBSERVED_PRESENT":"NOT_OBSERVABLE"},
  {key:"recommendations",title:"Recommended Actions",content:{recommendations:input.recommendations},evidenceRefs:[],confidence:"UNKNOWN",observability:input.recommendations.length?"OBSERVED_PRESENT":"NOT_OBSERVABLE"},
  {key:"measurement",title:"Measurement Readiness",content:{evidenceCoverage:input.evidenceCoverage},evidenceRefs:[],confidence:"UNKNOWN",observability:"OBSERVED_PRESENT"},
  {key:"limitations",title:"Limitations",content:{},evidenceRefs:[],confidence:"UNKNOWN",observability:"OBSERVED_PRESENT"}
]; const nextAction:ScoutNextAction={actionType:input.evidenceCoverage<50?"collect_missing_evidence":"review_audit",reason:input.evidenceCoverage<50?"Evidence coverage is insufficient for confident delivery":"Audit inputs are assembled for review",evidenceRefs:[],confidence:input.evidenceCoverage<50?"LOW":"MEDIUM",approvalLevel:"INTERNAL_REVIEW",missionType:input.evidenceCoverage<50?"collect_missing_evidence":"review_audit",status:"RECOMMENDED"}; const audit:MapSparkAudit={auditId:crypto.randomUUID(),businessId:(input.business as {id:string}).id,generatedAt:new Date().toISOString(),generatedBy:input.generatedBy,methodologyVersion:input.methodologyVersion,visibilityScore:input.visibilityScore,visibilityScoreVersion:"provided",opportunityScore:input.opportunityScore,opportunityScoreVersion:"provided",competitorBenchmark:input.competitorBenchmark,evidenceCoverage:input.evidenceCoverage,confidence:{},sections,findings:[],recommendations:input.recommendations,quickWins:input.quickWins,nextAction,approvalStatus:"NOT_REQUIRED",evidenceRefs:[],sourceRefs:[],limitations:["Audit consumes existing intelligence and does not independently verify all facts."],generatedArtifacts:[],status:"DRAFT"}; audit.evidenceRefs=collectAuditEvidence(audit); return {audit,findings:audit.findings,nextAction}; }
